apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app # Nome da aplicação para ser encontrado por services, etc.
spec:
  selector:
    matchLabels:
      app: react-app # Nome da aplicação para ser encontrado por services, etc.
  replicas: 1 # Número de replicas do pod
  template:
    metadata:
      labels:
        app: react-app # Nome da aplicação para ser encontrado por services, etc.
    spec:
      containers:
      - name: react-app
        image: DOCKER_IMAGE # Imagem que será utilizada no pod
        resources: # Recursos do cluster para esse pod
          limits: # Recursos máximos que o pod poderá utilizar
            memory: 100Mi
            cpu: 100m
          requests: # Recursos do cluster que será reservado para esse pod
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 80
